### ISSUE TITLE
Remain the tooltip for a sec

### ISSUE THREAD

**Issue by hedecan** [Tipue/Tipr#10]
Hi there,

It is a great tool. Just a quick request: Is there a way to remain the tooltip for a sec or 2 sec in order to let the user click on the link over the tooltip?
thank you

**Comment by Tipue** [comment]
See the speed option.

**Comment by hedecan** [comment]
Hi,

Speed option is to load the tooltip rather than remain on the screen for a while. I wanted to remain on the screen for a while once it is loaded.
