### ISSUE TITLE
Remain the tooltip for a sec

### ISSUE THREAD

**Issue by mehmetaltuntas** [Tipue/Tipr#11]
Hi,

Speed option is to load the tooltip rather than remain on the screen for a while. I wanted to remain on the screen for a while once it is loaded.

**Comment by Tipue** [comment]
Ah, I see. You'll have to get your hands dirty with a little JavaScript. Add the line $(tipr_cont).fadeOut(500) before line 51, $(tipr_cont).remove(); in tipr.js.

I'll include this as an option in the next release.

**Comment by hedecan** [comment]
Thank you.

The reason why I wanted was to have a link inner the tooltip, however, this doesn't seem working. 
I am literally assigning the following anchor to data-tip:
<a href="#">Send Message</a>

data-tip that doesn't seem accepting any HTML code for itself.  What would be the solution for me to bind a HTML code to data-tip ?
thank you

**Comment by Tipue** [comment]
Sorry, Tipr isn't really designed for that. You might want to look at http://www.tipue.com/popr/ which could be closer to what you're after.
