### ISSUE TITLE
Tooltip on absolutely positioned element

### ISSUE THREAD

**Issue by deronsizemore** [Tipue/Tipr#12]
a {
        display: block;
        float: left;
        height: 300px;
        position: relative;
    }

    a span {
	position: absolute;
	bottom: 15px;
	left: 50%;
	transform: translate(-50%, -50%);
    }

    <a href="" class="tip" data-tip="Click Here"><span>tooltip</span></a>

With the above code, I have a tooltip on the span element which is positioned absolutely so that I can center it and place it at the bottom of the parent anchor container. It seems though that having the span positioned absolutely that the tooltip only expands to the width of the contents of the span which means the text inside the tooltip wraps. Is the only way to fix this jus setting a static width on the tooltip itself in the .css?

**Comment by Tipue** [comment]
You can't set a static width, at least not without rewriting a fair bit of the css. Span is also an in-line element and shouldn't really have an absolute position. I would suggest enclosing the link in a block level element such as a div.

**Comment by deronsizemore** [comment]
Hmm. Ok. Maybe I'm only seeing it work because I haven't tested in all browsers yet, but if I set .tipr_content to width 150px (wide enough to accommodate the static text in my tooltip) it seems to work fine. 

The problem with my particular issue is that I have type of setup: http://i.imgur.com/T7Quhs7.png

Each color is an anchor and the Hex value at the bottom is the span. All I'm needing to do is keep the span (or div or whatever I use) centered and I only want the tooltip to pop up when that span is hovered. The catch seems to be that for me to center that Hex value and place it at the bottom of the anchor (color) it needs absolute positioning and with absolute positioning the tooltip width is only as wide as the span as you can see here: http://i.imgur.com/6QvCU8Z.png

**Comment by Tipue** [comment]
I'm not sure I have an answer off the bat but I suspect enclosing the tooltip in a div is the way forward.

**Comment by deronsizemore** [comment]
Sorry, I just noticed that I completely butchered my HTML above. Dang.

Here's what I actually have: 

    <a href="#"><span class="tip" data-tip="Click to Copy Hex">#3080cb</span></a>

I'm not sure if placing a div around the tooltip is still a solution or not here? I'm not sure what placing a div around it would do, but considering my HTML was wrong above, that may be where the confusion came from.

**Comment by Tipue** [comment]
I'm still unclear why you're using a span rather than a div. A div is easier to position.
