### ISSUE TITLE
Publish Tipr on npm?

### ISSUE THREAD

**Issue by lucidlemon** [Tipue/Tipr#15]
Hey there,
would it be possible to publish Tipr on npm? [Shouldn't be much of a problem](https://docs.npmjs.com/getting-started/publishing-npm-packages).

**Comment by Tipue** [comment]
I'll look into it for the next release.

**Comment by lucidlemon** [comment]
thanks a lot for this quick fix. really awesome. you rock. thanks. wow! 10/10
