### ISSUE TITLE
Incorrect top position calculation inside div with scrollbars

### ISSUE THREAD

**Issue by MelkorNemesis** [Tipue/Tipr#7]
When you bind tipr to element inside a ```<div></div>``` with scrollbar (i.e. ```overflow: auto;```) and you scroll, tooltip position is shifted. 

Can you please make a fix?

**Comment by MelkorNemesis** [comment]
Sorry, this issue was caused by not having ```position: relative;``` on parent element. Though it should be fixed anyway.

**Comment by Tipue** [comment]
Thanks. I'll look into it for the next release.
