### ISSUE TITLE
Add bower support

### ISSUE THREAD

**Issue by keeross** [Tipue/Tipr#8]
There is a tipr clone on Bower, or what so ever, but it was last updated 2 years ago.
So please, add bower init file and submit it.

**Comment by Tipue** [comment]
Done. I don't use Bower, so tell me if there's something else I need to include in the file.

**Comment by keeross** [comment]
You may follow this tutorial in order to submit it correctly. I assume, you'll have to add some more data to your bower.json file and then register it.
http://bower.io/docs/creating-packages/

**Comment by chrisvanpatten** [comment]
I think it's missing the "main" attribute, which tells Bower what the main JS file to include is. I'll add a PR.

**Comment by Tipue** [comment]
I've now updated this. Is it working now?

**Comment by chrisvanpatten** [comment]
Yep! Should be perfect once you tag a new version. I had to manually specify the commit hash so it picked up the latest changes to bower.json instead of the last tagged commit.

**Comment by Tipue** [comment]
I've edited the existing 2.0.1 tag and hopefully this will work.

**Comment by chrisvanpatten** [comment]
Looks like [Github is seeing those commits as ahead of the tag, not part of it](https://github.com/Tipue/Tipr/compare/2.0.1...master).

If you edited the tag locally you might just need to push --tags.

**Comment by Tipue** [comment]
How about now?

**Comment by chrisvanpatten** [comment]
Sadly no... the 2.0.1 tag doesn't show the bower.json file: https://github.com/Tipue/Tipr/tree/2.0.1

**Comment by Tipue** [comment]
I've released a new version, 2.0.2, so this should work now.

**Comment by chrisvanpatten** [comment]
Works perfectly! :rocket: :+1:

**Comment by Tipue** [comment]
Great. At last. :-)
